# Generated by Django 4.0.6 on 2022-07-29 08:12

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interests', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', core.fields.MandatoryTextField()),
                ('created_at', core.fields.DefaultFieldNow(default=django.utils.timezone.now)),
                ('last_updated_at', core.fields.OptionalTimestampField(blank=True, null=True)),
                ('title', core.fields.MandatoryCharField(max_length=250)),
                ('view_count', core.fields.OptionalBigIntegerField(blank=True, default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('interest_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.interestgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', core.fields.MandatoryTextField()),
                ('created_at', core.fields.DefaultFieldNow(default=django.utils.timezone.now)),
                ('last_updated_at', core.fields.OptionalTimestampField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', core.fields.MandatoryTextField()),
                ('created_at', core.fields.DefaultFieldNow(default=django.utils.timezone.now)),
                ('last_updated_at', core.fields.OptionalTimestampField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
