# Generated by Django 4.0.5 on 2022-06-14 19:46

import core.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', core.fields.UniqueCharField(max_length=30, unique=True)),
                ('slug', core.fields.UniqueCharField(max_length=30, unique=True)),
                ('description', core.fields.MandatoryCharField(max_length=150)),
                ('welcome', core.fields.MandatoryTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
